name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Genera la animación de la serpiente
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: kanekitakitos
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # Sube los archivos generados
      - uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      # Sube los cambios al repositorio
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
